### ISSUE TITLE
Broken deploy workflow

### ISSUE THREAD

**Issue by TimoDiepers** [brightway-lca/dynamic_characterization#4]
The package deploy workflow is currently not working: https://github.com/brightway-lca/dynamic_characterization/actions/runs/10942281505/job/30379115565

It works if the package does not yet exist on TestPyPi, but if it does it returns an Error (POST body may not contain duplicate keys). skip-existing: true is set in the workflow but it does not seem to do anything.

**Comment by TimoDiepers** [comment]
It could be a more general problem connected to this: https://github.com/pypi/warehouse/pull/16732

**Comment by TimoDiepers** [comment]
Other brightway packages (using a similar deploy workflow) also appear to be broken (https://github.com/brightway-lca/brightway2-data/actions/runs/10942520022/job/30379996447). 

@cmutel FYI, or if you happen to find out something's wrong in the workflow.yml or the pyproject.toml please let me know. This project is based on the bw cookie cutter template, so it could also be a more general problem them.

**Comment by TimoDiepers** [comment]
Fixed with https://github.com/pypi/warehouse/pull/16759

**Comment by cmutel** [comment]
Note that we have a solution to the "CI runs twice if a commit is tagged", will fix the template soon.
